# 1. Database Connection Settings
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate Dialect (Updated to avoid HHH90000025 warning)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 2. Server Port
server.port=${PORT}

# SendGrid API Configuration (replaces SMTP)
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.sender.email=coccrv109@gmail.com
sendgrid.sender.name=HirBee

# 4. Google OAuth2 Settings
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# 5. Multipart & Header Size
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
server.max-http-request-header-size=5MB
server.servlet.session.cookie.same-site=lax

# 6. Hibernate Settings
spring.jpa.properties.hibernate.type.descriptor.sql.variable_limit=2048

# 7. Razorpay Settings
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}

# 8. Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000